name: 'Build and publish Angular app'

on:
  workflow_run:
    workflows:
      - "Submodules Sync"
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build-and-deploy-app:
    concurrency: ci-${{ github.ref }} # For making multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CHECKOUT_PAT }}
          submodules: true


      - name: Update submodule 
        run: |
          ls docs/github_pages_app/personal-website
          git submodule update --remote docs/github_pages_app

      - name: Install dependencies
        run:  |
          cd docs/github_pages_app/personal-website 
          npm ci
          npm install

      - name: Build app
        run: |
          cd docs/github_pages_app/personal-website 
          cat package.json
          npm run-script deploy

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/github_pages_app/personal-website/dist/personal-website # The folder the action should deploy.