name: 'Build Angular app'

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install npm
        run:  |
          ls docs/
          (cd docs/github_pages_app/personal-website && npm install && npm build)

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: main # The branch the action should deploy to.
          folder: docs/github_pages_app/personal-website # The folder the action should deploy.